/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transorm 
Author: autoNgraphic (https://sketchfab.com/autoNgraphic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmw-f22-eurofighter-free-d4ffe0df9066481fa028eb1e1348c4b0
Title: BMW F22 "EUROFIGHTER" [FREE]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const BMW1 = (props) => {
  const { nodes, materials } = useGLTF('/bmw/bmw1/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.ALIUM2} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.TAIL_GLASS} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.bmw_logo__spec} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.cockpit_belt__spec} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.decals__spec} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.driftinghu__spec} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.mat_plastic_grey__spec} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.mat_metal_grey__spec} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.rad_prop__spec} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.remap__prim_env_2_spec} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.smw_remap__sec_env_4_spec} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.smw_remap__sec_env_4_spec} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.window__spec} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.wheelz__env_3_spec} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.wheelz__env_3_spec} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.ALIUM} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.ALIUM} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.ALIUM} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.BLACK} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.BLACK} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.BLACK} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.WINDOWS} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.ad08_sidewall__spec} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.ad08_sidewall__spec} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.advan__spec} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.enginesymbols2__spec} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.cooler__spec} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.brake_disc__env_4_spec} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.brake_disc__env_4_spec} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.brake_disc__env_4_spec} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.brake_disc__env_4_spec} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.bulloni_d__spec} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.cabin_ao__spec} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.cabin_ao__spec} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.cockpit_belt_door__spec} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.colors__spec} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.colors__spec} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.colors__spec} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.colors__spec} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.discextras__spec} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.mat_plastic_grey__spec} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.enginesymbols__spec} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.light_d__spec} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.interior_lod0__spec} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.interior_lod0__spec} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.mat_metal_grey__spec} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.mat_plastic_black__spec} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.mat_rubber_dark__spec} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.mirror__env_17_spec} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.remap__prim_env_2_spec} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.remap__prim_env_2_spec} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.remap__prim_env_2_spec} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.remap__prim_env_2_spec} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.remap__prim_env_2_spec} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.remap__prim_env_2_spec} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.remap__prim_env_2_spec} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.weld__spec} />
      </group>
    </group>
  )
}

useGLTF.preload('/bmw/bmw1/scene.gltf')
